### ISSUE TITLE
How should this documentation be made to look?

### ISSUE THREAD

**Issue by leoj3n** [bit-docs/bit-docs-js#8]
For this `documentjs.process.*` stuff:

https://github.com/bit-docs/bit-docs-js/blob/master/process/code.js

How should that documentation be updated?

I'm guessing `bit-docs/process/*` wouldn't make sense as a dumb search/replace.

I guess `@function documentjs.process.code` would become `@module code`?

And `@parent documentjs.process.methods` would become `@parent bit-docs/process/methods`?

Would `@signature documentjs.process.code(options, callback)`
become `@signature code(options, callback)`?

Would `@param {documentjs.process.processOptions} options`
become `@param {bit-docs/process/processOptions} options`?

Should `bit-docs/` above actually be `bit-docs-js/`?

**Comment by chasenlehara** [comment]
I think keeping the same structure as before makes sense. It’s a little easier to visualize the hierarchy in the current docs: https://documentjs.com/docs/documentjs.process.code.html

**Comment by chasenlehara** [comment]
> Should `bit-docs/` above actually be `bit-docs-js/`?

Yes, since they’re all part of this module now.

**Comment by leoj3n** [comment]
@chasenlehara thanks; I was obviously a bit confused in the beginning when I made this post, but this makes sense now.
